### ISSUE TITLE
API returning 404 NOT FOUND at http://localhost:3333/api

### ISSUE THREAD

**Issue by BBIEPavkov** [oktadev/okta-enterprise-ready-workshops#10]
My API keeps coming back stating cannot GET /api, or if I try to POST then I'm getting Cannot POST. Both errors are a 404, not found. The server is running on 3333 just like in the video. I'm not super familiar with testing with curl, so I thought maybe I was making a mistake there. I tried testing on Postman, with the same results. I tried doing a GET call with http://localhost:3333/api/todos as well as a few other endpoints listed in the main.ts file, and got an "unauthorized" response, so I know the API is running and "working" in some sense, but I cannot figure out why the other endpoints are returning not found. Any advice on how to troubleshoot this?

**Comment by alisaduncan** [comment]
Hey there @BBIEBates ! 
Do you see this when you try running the project in the `main` branch? Trying to make sure we start troubleshooting at this state:
https://developer.okta.com/blog/2023/07/27/enterprise-ready-getting-started

**Comment by BBIEPavkov** [comment]
Good morning! You can see my current code at my repo https://github.com/BBIEBates/okta-enterprise-ready-workshops

**Comment by BBIEPavkov** [comment]
I don't know what I did differently, but it seems to be functioning as it should now. Thanks for your response!

**Comment by alisaduncan** [comment]
Glad to hear it's working! Let us know if you run into any issues! You can add a comment/question to the blog post associated with the specific workshop you're working on.
